development:
  adapter: postgresql
  username: twg_dev
  password: twg_dev!
  min_messages: WARNING
  database: typewriter_api_dev
  host: localhost
  port: 5432

test:
  adapter: postgresql
  username: twg_dev
  password: twg_dev!
  min_messages: WARNING
  database: typewriter_api_test
  host: localhost
  port: 5432

production:
  adapter: postgresql
  username: twg_dev
  password: twg_dev!
  min_messages: WARNING
  database: typewriter_api_prod
  host: localhost
  port: 5432
